<?php
/**
 * Created by PhpStorm.
 * User: x_l
 * QQ:99628038
 * Date: 2016/12/26
 * Time: 15:08
 */

namespace common\models\tools;

use yii\base\Model;

class UploadImg extends Model
{

    /**
     * @var \yii\web\UploadedFile $imageFile
     */
    public $imageFile;

    public $path;

    public $name;

    public $out_name;

    //图片上传二级域
    public $img_service='http://'.DOMAIN_IMG;

    //图片上传物理目录
    public $img_service_physical_directory;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->img_service_physical_directory=\Yii::getAlias('@img').'/web';
    }

    public function rules()
    {
        return [
            [['imageFile'], 'file', 'skipOnEmpty' => false, 'extensions' => 'png,jpg',],
        ];
    }

    /**
     * 上传主函数
     * @return bool
     */
    public function upload()
    {
        if ($this->validate()) {
            if($this->out_name==''){
                if($this->name==''){
                    self::setName();
                }
                self::setOutName();
            }
            if(!is_file($this->out_name)){
                if($this->path){
                    if (!is_dir($this->img_service_physical_directory.'/'.$this->path)) {
                        mkdir($this->img_service_physical_directory.'/'.$this->path, 0755, true);
                    }
                }else{
                    $this->setPath();
                }
            }
            return $this->imageFile->saveAs($this->img_service_physical_directory.'/'.$this->out_name);
        } else {
            return false;
        }
    }

    /**
     * 获取文件名
     * @return mixed
     */
    public function getName(){
        return $this->name;
    }

    /**
     * 设置文件名
     * @param string $name
     */
    public function setName($name=''){
        if($name==''&&$this->name==''){
            $key = 'Arjit.-5)1imselfj';//随便写的加密KEY
            $this->name = md5($this->imageFile->baseName . $key . time() . microtime() . rand());
        }else{
            if($name){
                $this->name=$name;
            }
        }
    }

    /**
     * 设置上传后文件名包括路径与拓展名
     * @param string $name
     */
    public function setOutName($outName=''){
        if($outName==''&&$this->out_name==''){
            $this->out_name=$this->path . $this->name . '.' . $this->imageFile->extension;
        }else{
            if($outName){
                $this->out_name=$outName;
            }
        }
    }

    /**
     * 设置路径
     */
    public function setPath(){
        if($this->out_name){
            $file=pathinfo($this->out_name);
            $this->path=$file['dirname'];
        }else{
            $this->path='upload';
        }
        if (!is_dir($this->path)) {
            mkdir($this->path, 0755, true);
        }
    }

    public function getErrors($attribute = null)
    {
        $errors= parent::getErrors($attribute); // TODO: Change the autogenerated stub
        $errors_str='';
        foreach ($errors as $k=>$v){
            $errors.=$k;
            if(is_array($v)){
                foreach ($v as $vv){
                    $errors.=$v;
                }
            }elseif(is_string($v)){
                $errors.=$v;
            }
            $errors.=';';
        }
    }

}