<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 2017/1/12
 * Time: 11:27
 */

namespace common\controllers;

use yii\helpers\Url;

class UserloginController extends BaseController
{
   public function init()
   {
       parent::init(); // TODO: Change the autogenerated stub

   }

}